# 应用程序主配置文件

# -------------------------------------------
# 通用配置 (General Configuration)
# -------------------------------------------
general:
  log_level: "INFO"  # 日志级别 (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  temp_file_dir: "/tmp/pii_app" # 临时文件存储目录
  device: "cpu"
  gpu_id: 0
  
  # Gradio UI 相关设置 (如果适用)
  ui:
    theme: "default" # UI 主题
    share_ui: false   # 是否通过 Gradio 分享 UI
    server_name: "0.0.0.0"
    server_port: 7860

# -------------------------------------------
# 处理器配置 (Processor Configuration)
# -------------------------------------------
processor:
  audio_processor:
    supported_formats:
      - ".wav"
      - ".mp3"
      - ".flac"
      - ".ogg"
    enable_pii_detection: false
    reference_voices_dir: "data/audio/reference_voices"

  # 说话人分割配置
    diarization:
      enabled             : true
      auth_token          : "" # huggingface 访问令牌, 如果需要访问私有模型，请设置此值, 优先通过环境变量设置
      model               : "pyannote/speaker-diarization-3.1"
      min_speakers        : 1
      max_speakers        : 5
      min_segment_duration: 1.0
      segmentation_onset  : null  # 使用模型默认值
      min_duration_on     : null  # 使用模型默认值
      min_duration_off    : null  # 使用模型默认值

    # 语音转录配置
    transcription:
      model_size  : "base"  # tiny,       base,    small, medium, large-v1, large-v2, large-v3
      language    : null  # 目标语言，null表示自动检测
      compute_type: "float32"  # float16, float32, int8
      device      : null  # cuda,         cpu,     auto
      batch_size  : 1  # 批处理大小
      chunk_size  : 30  # 音频块大小（秒）

      # 对齐配置
      align_model           : null  # 对齐模型名称，null表示自动选择
      interpolate_method    : "nearest"  # 插值方法
      return_char_alignments: false  # 是否返回字符级对齐

      # VAD配置
      vad_onset           : 0.500  # VAD起始阈值
      vad_offset          : 0.363  # VAD结束阈值
      vad_min_duration_on : 0.0  # 最小激活时长
      vad_min_duration_off: 0.0  # 最小静默时长

      # 解码配置
      temperature                : 0.0  # 采样温度
      best_of                    : null  # 候选数量
      beam_size                  : null  # 束搜索大小
      patience                   : null  # 束搜索耐心值
      length_penalty             : null  # 长度惩罚
      suppress_tokens            : "-1"  # 抑制的令牌
      initial_prompt             : null  # 初始提示
      condition_on_previous_text : true  # 是否基于前文条件化
      fp16                       : true  # 是否使用半精度
      compression_ratio_threshold: 2.4  # 压缩率阈值
      logprob_threshold          : -1.0  # 对数概率阈值
      no_speech_threshold        : 0.6  # 无语音阈值

    # 语音转换配置
    voice_conversion:
      diffusion_steps: 10
      length_adjust: 1.0
      inference_cfg_rate: 0.7
      f0_condition: true
      auto_f0_adjust: true
      default_pitch_shift: 0

    # 语音匿名化配置
    voice_anonymizer:
      enabled: true
      sample_rate: 22050
      
      # 蜂鸣音设置
      beep_frequency: 1000.0    # 蜂鸣音频率（Hz）
      beep_amplitude: 0.3       # 蜂鸣音音量（0-1）
      
      # 通用设置
      fade_duration: 0.05       # 淡入淡出时长（秒）

  text_processor:
    supported_entities:
      - PERSON
      - PHONE_NUMBER
      - ID_CARD
      - BANK_CARD
      - CARD_ID
      - EMAIL_ADDRESS
      - CREDIT_CARD
      - CAR_PLATE
      - ADDRESS
      - DATE_TIME
      - IP_ADDRESS
      - MAC_ADDRESS
      - LOCATION
      - ALL
    exclude_entities:
      - NONE
    analyzer:
      presidio_enabled          : true
      supported_languages       : ["zh", "en"]
      default_language          : "zh"
      enable_pattern_recognizers: true
      enable_llm_recognizers    : true
      default_score_threshold   : 0.5
      parallel_processing       : false
      max_workers               : 4
      enable_cache              : true
      cache_size                : 1000
      
    anonymizer:
      presidio_enabled: true
      anonymization_strategy: "replace"  # 统一的匿名化策略
      operator_params:  # 统一的操作符参数
        new_value: "[REDACTED]"
        masking_char: "*"
        chars_to_mask: -1
        from_end: true
        hash_type: "sha256"
      entity_anonymization_config:  # 保留原有的实体特定配置作为备选
        PERSON:
          operator: "replace"
          params:
            new_value: "[PERSON]"
        PHONE_NUMBER:
          operator: "mask"
          params:
            masking_char: "*"
            chars_to_mask: 7
            from_end: true
        ID_CARD:
          operator: "mask"
          params:
            masking_char: "*"
            chars_to_mask: 12
            from_end: false
        BANK_CARD:
          operator: "mask"
          params:
            masking_char: "*"
            chars_to_mask: 12
            from_end: false
        EMAIL_ADDRESS:
          operator: "replace"
          params:
            new_value: "[EMAIL]"
        URL:
          operator: "replace"
          params:
            new_value: "[URL]"
      keep_original_score: false
      validate_anonymization: true
      
    segmentation:
      segmentation_strategy: "sentence"
      sentence_segmentation:
        use_spacy: true
        spacy_model: "zh_core_web_sm"
        custom_patterns: ["[。！？]", "[.!?]"]
        min_sentence_length: 5
        max_sentence_length: 1000
      paragraph_segmentation:
        paragraph_separators: ["\n\n", "\r\n\r\n"]
        min_paragraph_length: 10
        max_paragraph_length: 5000
      fixed_length_segmentation:
        chunk_size: 500
        overlap_size: 50
        respect_word_boundaries: true
      custom_segmentation:  # 添加自定义分割配置
        custom_patterns: []
        custom_function: null
      post_processing:
        remove_empty_segments: true
        strip_whitespace: true
        min_segment_length: 1
        max_segment_length: 10000
      parallel_processing: false
      enable_cache: true
      cache_size: 500
    
    # 识别器配置
    recognizers:
      pattern_recognizer:
        enabled     : true
        id_card     : true
        phone_number: true
        bank_card   : true
        car_plate   : true
        url         : true
      llm_recognizer:
        enabled: true  # 启用LLM识别器
        client:
            type              : "gemini"  # 使用Gemini客户端
            model_name_or_path: "gemini-2.5-flash-preview-05-20"  # 使用最新的Gemini模型
            temperature       : 0  # 修正参数名（从temperatures改为temperature）
            max_tokens        : 20000  # 设置最大token数
            top_p             : 0.9
            top_k             : 50
          # api_key           : "YOUR_API_KEY"  # 请替换为您的API密钥或通过环境变量GEMINI_API_KEY设置
        prompts:
          prompt_template_path: "config/prompt_template.yaml"
        parsers:
          example: "default"
