# 音频处理默认配置

# 支持的音频格式
supported_formats:
  file_types:
    - ".wav"
    - ".mp3"
    - ".flac"
    - ".ogg"

# 说话人分割配置
diarization:
  model: "pyannote/speaker-diarization-3.1"
  min_speakers: 1
  max_speakers: 5
  min_segment_duration: 1.0
  segmentation_onset: null  # 使用模型默认值
  min_duration_on: null     # 使用模型默认值
  min_duration_off: null    # 使用模型默认值

# 语音转换配置
voice_conversion:
  diffusion_steps: 10
  length_adjust: 1.0
  inference_cfg_rate: 0.7
  f0_condition: true
  auto_f0_adjust: true
  default_pitch_shift: 0

# PII检测配置
enable_pii_detection: false

# 参考声音目录路径
# 如果为null，将使用代码中设置的默认路径
reference_voices_dir: null